services:
  postgres-users:
    image: postgres:16
    container_name: tripactive-postgres-users
    restart: always
    environment:
      POSTGRES_USER: tripactive
      POSTGRES_PASSWORD: tripactive
      POSTGRES_DB: tripactive_users
    ports:
      - "5433:5432"
    volumes:
      - pgdata_users:/var/lib/postgresql/data
    networks:
      - tripactive-net

  postgres-activities:
    image: postgres:16
    container_name: tripactivc-postgres-activities
    restart: always
    environment:
      POSTGRES_USER: tripactive
      POSTGRES_PASSWORD: tripactive
      POSTGRES_DB: tripactive_activities
    ports:
      - "5434:5432"
    volumes:
      - pgdata_activities:/var/lib/postgresql/data
    networks:
      - tripactive-net

  postgres-bookings:
    image: postgres:16
    container_name: tripactive-postgres-bookings
    restart: always
    environment:
      POSTGRES_USER: tripactive
      POSTGRES_PASSWORD: tripactive
      POSTGRES_DB: tripactive_bookings
    ports:
      - "5435:5432"
    volumes:
      - pgdata_bookings:/var/lib/postgresql/data
    networks:
      - tripactive-net

  postgres-auth:
    image: postgres:16
    container_name: tripactive-postgres-auth
    restart: always
    environment:
      POSTGRES_USER: tripactive
      POSTGRES_PASSWORD: tripactive
      POSTGRES_DB: tripactive_auth
    ports:
      - "5436:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    networks:
      - tripactive-net

  users:
    build:
      context: .
      dockerfile: cmd/users/Dockerfile
    container_name: tripactive-users
    ports:
      - "8081:8081"
    env_file: cmd/users/.env
    environment:
      DATABASE_URL: postgres://tripactive:tripactive@postgres-tripactive:5432/tripactive_users?sslmode=disable
    depends_on:
      - postgres-users
    networks:
      - tripactive-net

  activities:
    build:
      context: .
      dockerfile: cmd/activities/Dockerfile
    container_name: tripactive-activities
    ports:
      - "8082:8082"
    env_file: cmd/activities/.env
    environment:
      DATABASE_URL: postgres://tripactive:tripactive@postgres-tripactive:5432/tripactive_activities?sslmode=disable
    depends_on:
      - postgres-activities
    networks:
      - tripactive-net

  bookings:
    build:
      context: .
      dockerfile: cmd/bookings/Dockerfile
    container_name: tripactive-bookings
    ports:
      - "8083:8083"
    env_file: cmd/bookings/.env
    environment:
      DATABASE_URL: postgres://tripactive:tripactive@postgres-tripactive:5432/tripactive_bookings?sslmode=disable
    depends_on:
      - postgres-bookings
    networks:
      - tripactive-net

  auth:
    build:
      context: .
      dockerfile: cmd/auth/Dockerfile
    container_name: tripactive-auth
    ports:
      - "8084:8084"
    env_file: cmd/auth/.env
    environment:
      DATABASE_URL: postgres://tripactive:tripactive@postgres-tripactive:5432/tripactive_auth?sslmode=disable
    depends_on:
      - postgres-auth
    networks:
      - tripactive-net

networks:
  tripactive-net:

volumes:
  pgdata_users:
  pgdata_activities:
  pgdata_bookings:
  pgdata_auth:
